//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class production
    {
        public long prod_id { get; set; }
        public System.DateTime prod_date { get; set; }
        public Nullable<decimal> prod_value { get; set; }
        public decimal prod_minCounter { get; set; }
        public decimal prod_maxCounter { get; set; }
        public int art_id { get; set; }
        public int loc_id { get; set; }
        public int dev_id { get; set; }
    
        public virtual article article { get; set; }
        public virtual device device { get; set; }
        public virtual location location { get; set; }
    }
}
