//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dailyProduction
    {
        public System.DateTime PROD_DATE { get; set; }
        public string LOCATION { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public string UNIT { get; set; }
        public string ARTICLE { get; set; }
    }
}
