//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagementWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class usage
    {
        public long use_id { get; set; }
        public System.DateTime use_date { get; set; }
        public Nullable<decimal> use_value { get; set; }
        public decimal use_minCounter { get; set; }
        public decimal use_maxCounter { get; set; }
        public int con_id { get; set; }
        public int loc_id { get; set; }
        public int dev_id { get; set; }
    
        public virtual consumption consumption { get; set; }
        public virtual device device { get; set; }
        public virtual location location { get; set; }
    }
}
